### ISSUE TITLE
Seems do not work on my neovim

### ISSUE THREAD

**Issue by tan-wei** [jay-babu/colorscheme-randomizer.nvim#3]
This is great. Buut Why do I always print the following message, no matter how I configure the plugin:
```
vim.cmd.colorscheme(nil)
default
```

This is my configure code (and I do use `Lazy.nvim` to install the plugin and colorschemes):
```lua
local status_ok, colorscheme_randomizer = pcall(require, "colorscheme-randomizer")

if not status_ok then
  local colorscheme = "tokyonight"

  local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
  if not status_ok then
    return
  end
end

colorscheme_randomizer.setup {
  apply_scheme = true,
  plugin_strategy = nil,
  plugins = nil,
  colorschemes = { "tokyonight" },
  exclude_colorschemes = nil,
}

```

**Comment by tan-wei** [comment]
Noticed that the plugin try to detect colorchemes in the `stdpath`. So is it here causing the problem?

**Comment by tan-wei** [comment]
The complete configuration is [here](https://github.com/tan-wei/neovim-init.lua)

**Comment by tan-wei** [comment]
OK. I know why I occurred this. Checkpoints will cause this problem, after I remove the checkpoint file manually, it works.

I can reproduce this problem by the following steps:
  1. The first time , config `colorscheme-randomizer` with None of scheme, now the checkpoints file saved
  2. The second time, config it with several color schemes with setting field `colorschemes`

Now every time we start neovim, it will only use default color scheme. But if we remove checkpoints file, it will work well. I think it is a bug... Suppose we install a new color scheme, we should manually remove the checkpoints file.

**Comment by jay-babu** [comment]
> OK. I know why I occurred this. Checkpoints will cause this problem, after I remove the checkpoint file manually, it works.
> 
> I can reproduce this problem by the following steps:
> 
> 1. The first time , config `colorscheme-randomizer` with None of scheme, now the checkpoints file saved
> 2. The second time, config it with several color schemes with setting field `colorschemes`
> 
> Now every time we start neovim, it will only use default color scheme. But if we remove checkpoints file, it will work well. I think it is a bug... Suppose we install a new color scheme, we should manually remove the checkpoints file.

yeah, should probably add a way to disable cache, delete it easily, or expire it every so often. feel free to create a PR, otherwise i will do so when i get the chance

**Comment by jay-babu** [comment]
also, can use versioning. 1.1.0 which adds cache support is not released: https://github.com/jay-babu/colorscheme-randomizer.nvim/pull/2. won't release it till this issue is addressed

**Comment by tan-wei** [comment]
Got it. I suggest that give the user an option to enable cache support is a better way. For me, I use lots of colorschemes, it is not that important to prevent from choosing the same colorscheme between two startups.
